<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="ur5_robot" >

  <xacro:property name="PI" value="3.14159265359"/>
  <xacro:property name="flange_radius" value="0.04"/>
  <xacro:property name="flange_offset" value="0.08"/>
  <xacro:property name="tool_tip_width" value="0.005"/>
  <xacro:property name="tool_tip_length" value="0.08"/>
  <xacro:property name="tool_extent_width" value="0.04"/>
  <xacro:property name="tool_extent_length" value="0.02"/>
  <xacro:property name="tool_body_width" value="0.04"/>
  <xacro:property name="tool_body_length" value="0.06"/>
  <xacro:property name="tool_length" value="${0.5*tool_body_length + tool_tip_length}"/>
  <xacro:arg name="ns" default=""/>

  <!-- common stuff -->
  <xacro:include filename="$(find ur5_vel_start)/urdf/common.gazebo.xacro" />

  <!-- ur5 -->
  <xacro:include filename="$(find ur5_vel_start)/urdf/ur5.urdf.xacro" />

  <!-- arm -->
  <xacro:ur5_robot prefix="$(arg ns)" joint_limited="true"/>

  <link name="world" />

  <joint name="world_joint" type="fixed">
    <parent link="world" />
    <child link = "$(arg ns)base_link" />
    <origin xyz="5.0 0.0 0.1" rpy="0.0 0.0 0.0" />
  </joint>



</robot>
