# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# Joint Velocity Controller - velocity based -------------------------------
ur5_velocity_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints:
     - $(arg ns)shoulder_pan_joint
     - $(arg ns)shoulder_lift_joint
     - $(arg ns)elbow_joint
     - $(arg ns)wrist_1_joint
     - $(arg ns)wrist_2_joint
     - $(arg ns)wrist_3_joint

ur5_velocity_controller_moveit:
  type: velocity_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 1, goal: 0.1}
      elbow_joint: {trajectory: 1, goal: 0.1}
      wrist_1_joint: {trajectory: 1, goal: 0.1}
      wrist_2_joint: {trajectory: 1, goal: 0.1}
      wrist_3_joint: {trajectory: 1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    shoulder_pan_joint:  {p: 10,  i: 0, d: 0, i_clamp: 1}
    shoulder_lift_joint: {p: 10,  i: 0, d: 0, i_clamp: 1}
    elbow_joint:         {p: 10,  i: 0, d: 0, i_clamp: 1}
    wrist_1_joint:       {p: 5,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist_2_joint:       {p: 5,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist_3_joint:       {p: 5,  i: 0.0, d: 0.1, i_clamp: 1}

