# In this scenario:
# - there is one order of two kits.
# - unreachale drops make the order impossible to complete.

# Competition configuration options
options:
  insert_models_over_bins: true     # Whether or not to insert the models that are specified in models_over_bins
  fill_demo_tray: false             # If true, AGV1's tray will have parts from the first order spawned
                                    # directly ontop of it once the competition starts (for testing purposes)
  gazebo_state_logging: true        # Whether or not to generate a gazebo state log
  model_type_aliases:               # Aliases for model types which can be used in the configuration file
    unreachable_drop_part_1: piston_rod_part
    unreachable_drop_part_2: gear_part
    order_part1: piston_rod_part
    order_part2: gear_part

# Orders to announce during the game
orders:
  order_0:
    announcement_condition: time     # Announce the order base on elapsed time
    announcement_condition_value: 0  # Time in seconds to wait before announcing the order
    kit_count: 2                     # How many of the same kit are in the order
    parts:                           # List of parts required to be in the kit
      part_0:
        type: order_part1            # Type of model required
        pose:
          xyz: [0.1, -0.15, 0]       # Position required in the kit tray frame
          rpy: [0, 0, 'pi/2']        # Orientation required in the kit tray frame
      part_1:
        type: order_part1
        pose:
          xyz: [-0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']
      part_2:
        type: order_part2
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: order_part2
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 0]

drops:
  drop_regions:
    agv1_unreachable_1:
      min:
        xyz: [0.0, 2.7, 0.6]
      max:
        xyz: [0.6, 3.5, 1.5]
      destination:
        xyz: [0.6, 3.1, 1.0]
        rpy: [0, 0, 0.2]
      part_type_to_drop: unreachable_drop_part_1
    agv2_unreachable_1:
      min:
        xyz: [0.0, -2.7, 0.6]
      max:
        xyz: [0.6, -3.5, 1.5]
      destination:
        xyz: [0.6, -3.1, 1.0]
        rpy: [0, 0, -0.2]
      part_type_to_drop: unreachable_drop_part_1

    agv1_unreachable_2:
      min:
        xyz: [0.0, 2.7, 0.6]
      max:
        xyz: [0.6, 3.5, 1.5]
      destination:
        xyz: [0.6, 3.1, 1.0]
        rpy: [0, 0, 0.15]
      part_type_to_drop: unreachable_drop_part_2
    agv2_unreachable_2:
      min:
        xyz: [0.0, -2.7, 0.6]
      max:
        xyz: [0.6, -3.5, 1.5]
      destination:
        xyz: [0.6, -3.1, 1.0]
        rpy: [0, 0, -0.15]
      part_type_to_drop: unreachable_drop_part_2

# Models to be inserted in the bins
models_over_bins:
  bin8:                              # Name of the bin (bin1-bin8, as named in the environment simulation)
    models:                          # List of models to insert
      pulley_part:                   # Type of model to insert
        xyz_start: [0.15, 0.15, 0.]  # Origin of the first model to insert
        xyz_end: [0.45, 0.45, 0.0]   # Origin of the last model to insert
        rpy: [0, 0, 'pi/4']          # Orientation of all models to insert
        num_models_x: 2              # How many models to insert along the x dimension
        num_models_y: 2              # How many models to insert along the y dimension

  bin6:
    models:
      piston_rod_part:
        xyz_start: [0.25, 0.25, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 'pi/3']
        num_models_x: 2
        num_models_y: 2

  bin5:
    models:
       gear_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 2
