# In this scenario:
# - there is one order of two kits.
# - there are faulty parts.
# - the belt is used and objects appear faster than usual.
# - there's need to flip some part.

options:
  insert_models_over_bins: true
  fill_demo_tray: false
  gazebo_state_logging: true
  belt_population_cycles: 8
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gasket_part
    order_part3: pulley_part
    order_part4: disk_part

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    kit_count: 2
    parts:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.19, 0]
          rpy: [0, 0, '-pi/4']
      part_1:
        type: order_part2
        pose:
          xyz: [-0.11, -0.21, 0]
          rpy: [0, 0, '-pi/4']
      part_2:
        type: order_part3
        pose:
          xyz: [-0.08, 0.17, 0]
          rpy: ['pi', 0, 'pi/2']
      part_3:
        type: disk_part
        pose:
          xyz: [0.15, 0.16, 0]
          rpy: [0, 0, 0]

faulty_parts:
  - gasket_part_8
  - gasket_part_3

belt_parts:
  piston_rod_part:
    5:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

  disk_part:
    10:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

  gasket_part:
    15:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

models_over_bins:
  bin5:
    models:
      pulley_part:
        xyz_start: [0.16, 0.16, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 'pi/3']
        num_models_x: 1
        num_models_y: 2
  bin6:
    models:
       gasket_part:
        xyz_start: [0.13, 0.13, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3

time_limit: 500
