# In this scenario:
# - There is one order of two kits.
# - There are faulty parts.
# - The belt is used.
# - There's no need to flip any parts.

options:
  insert_models_over_bins: true
  fill_demo_tray: false
  gazebo_state_logging: true
  belt_population_cycles: 5
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gear_part
    order_part3: pulley_part
    order_part4: disk_part

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    kit_count: 2
    parts:
      part_0:
        type: order_part2
        pose:
          xyz: [0.1, -0.18, 0]
          rpy: [0, 0, 'pi/4']
      part_1:
        type: order_part3
        pose:
          xyz: [-0.12, -0.2, 0]
          rpy: [0, 0, 'pi/4']
      part_2:
        type: order_part1
        pose:
          xyz: [-0.09, 0.16, 0]
          rpy: [0, 0, 'pi/4']
      part_3:
        type: order_part4
        pose:
          xyz: [0.09, 0.16, 0]
          rpy: [0, 0, '-pi/4']

faulty_parts:
  - piston_rod_part_3
  - disk_part_4

belt_parts:
  gear_part:
    8:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

  piston_rod_part:
    12:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/2']

  disk_part:
    16:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

models_over_bins:
  bin6:
    models:
      piston_rod_part:
        xyz_start: [0.21, 0.21, 0.0]
        xyz_end: [0.41, 0.41, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2
  bin7:
    models:
       pulley_part:
        xyz_start: [0.14, 0.14, 0.0]
        xyz_end: [0.46, 0.46, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 1
  bin8:
    models:
      disk_part:
        xyz_start: [0.14, 0.14, 0.0]
        xyz_end: [0.46, 0.46, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

time_limit: 500
