# In this scenario:
# - There are two orders of one tray each:
#   - The second will interrupt the first at a time that is convenient for the second order.
#   - Teams can choose to re-purpose the parts in the tray for the new order.
#   - After the second order is complete, the first order is to be resumed.
# - There are no faulty parts.
# - The belt is used.
# - There's no need to flip any part.

options:
  insert_models_over_bins: true
  fill_demo_tray: false
  gazebo_state_logging: true
  belt_population_cycles: 5
  model_type_aliases:
    order_part1: disk_part
    order_part2: piston_rod_part
    order_part3: pulley_part
    order_part4: gear_part

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    kit_count: 1
    parts:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.18, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part2
        pose:
          xyz: [-0.12, -0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: order_part2
        pose:
          xyz: [-0.12, 0.2, 0]
          rpy: [0, 0, 'pi']
      part_3:
        type: order_part3
        pose:
          xyz: [0.1, 0.17, 0]
          rpy: [0, 0, 0]
  order_1:
    announcement_condition: wanted_parts
    announcement_condition_value: 3
    kit_count: 1
    parts:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.18, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part2
        pose:
          xyz: [-0.12, -0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: order_part2
        pose:
          xyz: [-0.12, 0.1, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part4
        pose:
          xyz: [0.1, 0.17, 0]
          rpy: [0, 0, 0]

belt_parts:
  piston_rod_part:
    10:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/2']

  gear_part:
    20:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

models_over_bins:
  bin7:
    models:
      disk_part:
        xyz_start: [0.16, 0.16, 0.0]
        xyz_end: [0.46, 0.46, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

  bin8:
    models:
      pulley_part:
        xyz_start: [0.16, 0.16, 0.0]
        xyz_end: [0.46, 0.46, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

time_limit: 500
